### ISSUE TITLE
Any reason why this hasn't been submitted to the App Store?

### ISSUE THREAD

**Issue by paulj** [mastahyeti/security-key#7]
Sorry to ask this via an issue, but it seemed the best way to reach out.

This app works really well as a way to enable U2F support on iPhones, especially given that Bluetooth Yubikeys still seem to be a long way off. I'm looking to roll it out amongst a handful of staff at my company, and I'm working out the options for how to distribute it. I can't seem to find it in the App Store, so I was wondering if that was because you didn't want to have to support it there, or if there was something in the code that made it unlikely to pass review?

(I know another option is an Enterprise certificate, I just wanted to understand if there were other options first)

**Comment by btoews** [comment]
There are a couple reasons I haven't published this. This first is that I don't want to deal with maintaining an app in the app store. I had been reaching out to companies that publish popular security apps to see if they would want to include the extension in their apps. One company started working on it, but the project stalled out. The other reason is that it requires a polyfill in order to work for any given site. I reached out to folks at other companies that use U2F (Google, Facebook, Dropbox, etc...). There was a bit of interest in adding the polyfill, but nothing ever happened.

**Comment by paulj** [comment]
Thanks for the clarification. A bit unfortunate that the polyfill causes so many issues.
